### ISSUE TITLE
TypeError: a.toDataURL is not a function

### ISSUE THREAD

**Issue by iwebroot** [DonRai/react-image-webp#83]
Hello,

I try this packages with [Remix Framework](https://remix.run) and I have this error :
```
TypeError: a.toDataURL is not a function
    at exports.isWebpSupported (/home/iwebroot/www/public_html/iwr/website/node_modules/react-image-webp/dist/utils/index.js:1:530)
    at Image (/home/iwebroot/www/public_html/iwr/website/node_modules/react-image-webp/dist/index.js:1:738)
```

Cordialy,
iWebRoot

**Comment by ovesh-ampush** [comment]
same i have also getiing this error
